# Generated by Django 4.0.6 on 2022-08-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.URLField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
